version: "3.9"

services:
  db:
    image: postgres:15
    container_name: supermarket_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zlagoda
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: supermarket_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: supermarket_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data: